#! /usr/bin/dh-exec --with-scripts=filter-arch,filter-build-profiles

usr/bin/gettextize
usr/bin/msgattrib
usr/bin/msgcat
usr/bin/msgcmp
usr/bin/msgcomm
usr/bin/msgconv
usr/bin/msgen
usr/bin/msgexec
usr/bin/msgfilter
usr/bin/msgfmt
usr/bin/msggrep
usr/bin/msginit
usr/bin/msgmerge
usr/bin/msgunfmt
usr/bin/msguniq
usr/bin/recode-sr-latin
usr/bin/xgettext

usr/libexec/gettext/cldr-plurals
usr/libexec/gettext/hostname
usr/libexec/gettext/project-id
usr/libexec/gettext/urlget
usr/libexec/gettext/user-email
usr/lib/*/libgettextlib-*.so
usr/lib/*/libgettextsrc-*.so
usr/lib/*/libtextstyle.so.*
usr/lib/*/preloadable_libintl.so

usr/share/aclocal/*.m4
usr/share/locale/*/*/gettext-tools.mo

usr/share/gettext/ABOUT-NLS
usr/share/gettext/config.rpath
usr/share/gettext/gettext.h
usr/share/gettext/msgunfmt.tcl
usr/share/gettext/disclaim-translations.txt
usr/share/gettext/schema/*

# The following two files are installed:
# A) If the architecture supports Java
# AND
# B) If build profile "nojava" has not been selected
[!hppa !hurd-any !kfreebsd-any] <!nojava> usr/share/gettext/gettext.jar usr/share/java
[!hppa !hurd-any !kfreebsd-any] <!nojava> usr/share/gettext/javaversion.class

usr/share/gettext/po/
usr/share/gettext/projects/
usr/share/gettext/styles/
usr/share/gettext-*/its/
